# This is a basic workflow to help you get started with Actions

name: iOS SDK unit test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
  push:
    branches: 
      - fc_staging

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode 11
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
    - name: GO to HotlineSDK
      run: cd HotlineSDK
    - name: Current Directory
      run: pwd
    - name: Run tests
      run: xcodebuild test -project "HotlineSDK.xcodeproj" -scheme "FreshchatSDKTest" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"
